### ISSUE TITLE
I tried but not managed to working...

### ISSUE THREAD

**Issue by MuchoTub** [matrixant/serial_port#2]
Hello. Thank you for your wonderful add-on!
Sorry, I am completely noob with these compiling things.
But, I need to use serial with Godot 4, I tried to compile the add-on.
I think I managed to compile as "plugin", but Godot 4.1 give me the error.
(serialport.windows.template_debug.x86_64.dll and other two files are generated in bin folder.)

  core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/serialport/serialport.gdextension
  Failed loading resource: res://addons/serialport/serialport.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

Is there way to fix this, and get it working?
I apologies my lack of knowledge, Please help me.

**Comment by MuchoTub** [comment]
It also fail to compile Godot, with serial_port files in the "module".....

**Comment by matrixant** [comment]
> 

In godot 4.1 some extention api has changed. I've compiled the plugin for godot 4.1 now, and you can find it in the release page. Download it and extract it directly to your project directory to use it.

**Comment by MuchoTub** [comment]
Thank you ! It worked !! 
Thank you very very much!!!

**Comment by matrixant** [comment]
My pleasure, I'll close the issue.
