### ISSUE TITLE
Compiling problem on linux with the 4.1 update

### ISSUE THREAD

**Issue by epthegeek** [matrixant/serial_port#3]
I've been using your fantastic module in a project, compiled in as a module rather than a plugin.  With the latest commit to the repo it's no longer compiling successfully for me -- have any of the requirements or build instructions changed?  I didn't see any changes to the readme about those things in the commit.  I did notice that 2 of the submodule repos changed; that's what has me wondering if I need any new pre-reqs or anything.

I'll attach the compile output from where it started to go wrong.

[compile_output.txt](https://github.com/matrixant/serial_port/files/12194866/compile_output.txt)

**Comment by epthegeek** [comment]
Oh - or is it a 4.1.1 versus 4.1.0 issue?

**Comment by matrixant** [comment]
> 

It's not a Godot issue, it's that I didn't update the module to 4.1. Of course, this can also be seen as a problem caused by the Godot 4.1 update.:P
You can use the plugin released in plugin branch before i update the module.

**Comment by matrixant** [comment]
> I've been using your fantastic module in a project, compiled in as a module rather than a plugin. With the latest commit to the repo it's no longer compiling successfully for me -- have any of the requirements or build instructions changed? I didn't see any changes to the readme about those things in the commit. I did notice that 2 of the submodule repos changed; that's what has me wondering if I need any new pre-reqs or anything.
> 
> I'll attach the compile output from where it started to go wrong.
> 
> [compile_output.txt](https://github.com/matrixant/serial_port/files/12194866/compile_output.txt)

I noticed that you may have cloned the plugin branch (I set it as default branch a few days ago), and now that I have added the module branch separately and updated the README file, you can follow it to build the module.

**Comment by epthegeek** [comment]
Ah! Yeah, I missed that difference. Thanks much for the info/updates! Will give it another shot.

**Comment by epthegeek** [comment]
Compiled just fine with the branch switch.  Thanks again!
